import { burger } from "./modules/burger/export-burger"
import { basket } from "./modules/basket/basket-export"
import { basketClose } from "./modules/basket/basket-export"
import { createBasket } from "./modules/basket/basket-export"
import { registration } from "./modules/authentication/registrtation-export"
import { btnUp } from "./components/btn-up/export-btnUp"