import { burger } from "./modules/burger/export-burger.js"
import { basket } from "./modules/basket/basket-export.js"
import { basketClose } from "./modules/basket/basket-export.js"
import { createBasket } from "./modules/basket/basket-export.js"
import { registration } from "./modules/authentication/registration/registration-export.js"
import { registration } from "./modules/authentication/login/Login.js"
import { btnUp } from "./components/btn-up/export-btnUp.js"
import { alert } from "../app/core/utils/alertMessage.js"